### PR TITLE
Use EJS v2

### LINKED ISSUE #4: EJS Version
Is there a reason why this uses the old, unmaintained, EJS v1 (tj/ejs) instead of v2 (mde/ejs)? I was thinking maybe mde/ejs should link to this, but I see you're not using our version of the lib.

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #4.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
👍

**Comment by RyanZim** [comment]
@IonicaBizau BTW, wouldn't this be a breaking change?

**Comment by IonicaBizau** [comment]
Yes, it is. 😂

https://ionicabizau.github.io/ejs-playground/

Can you please take care of that and submit a new PR fixing it?

**Comment by IonicaBizau** [comment]
Oh, actually it does work in Chrome!

**Comment by RyanZim** [comment]
Sorry, wanted to say that in the OP, but forgot; and the PR merged just as I hit Comment. 

> Can you please take care of that and submit a new PR fixing it?

You mean just bump the version in the package.json?

**Comment by IonicaBizau** [comment]
@RyanZim It seems to be broken in Safari, but works fine in Chrome. I can easily bump the version, but I'm not really sure why it's not working in Safari. I'm not even sure if it worked before. 😁

**Comment by IonicaBizau** [comment]
No worries, it never worked in Safari: https://rawgit.com/IonicaBizau/ejs-playground/9f06c7c4dc119850ffa41f5642100c3210ec7ec8/index.html

**Comment by RyanZim** [comment]
I was referring to the fact that EJS v1 code doesn't always work in v2.

**Comment by IonicaBizau** [comment]
True. I released `2.0.0` 🚢

**Pull request merged**
